// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgMrL8bd-31H8XhC_sYEU9zZ2MpkqZUJ0',
    appId: '1:33694523887:web:974326c9f8ce97fb9e561a',
    messagingSenderId: '33694523887',
    projectId: 'test-950bf',
    authDomain: 'test-950bf.firebaseapp.com',
    storageBucket: 'test-950bf.firebasestorage.app',
    measurementId: 'G-YQLGL8S99V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-c4hOPBcdVjWQQRBBqVKNbuc5Zmichs',
    appId: '1:33694523887:android:fd859ce3ea7437359e561a',
    messagingSenderId: '33694523887',
    projectId: 'test-950bf',
    storageBucket: 'test-950bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzSxLnEKAr1b33VyedejX14uj8_E_W8E',
    appId: '1:33694523887:ios:cb5a629ba8df7ee09e561a',
    messagingSenderId: '33694523887',
    projectId: 'test-950bf',
    storageBucket: 'test-950bf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApzSxLnEKAr1b33VyedejX14uj8_E_W8E',
    appId: '1:33694523887:ios:cb5a629ba8df7ee09e561a',
    messagingSenderId: '33694523887',
    projectId: 'test-950bf',
    storageBucket: 'test-950bf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgMrL8bd-31H8XhC_sYEU9zZ2MpkqZUJ0',
    appId: '1:33694523887:web:e9057a35c311b1159e561a',
    messagingSenderId: '33694523887',
    projectId: 'test-950bf',
    authDomain: 'test-950bf.firebaseapp.com',
    storageBucket: 'test-950bf.firebasestorage.app',
    measurementId: 'G-9P3VT18HVR',
  );
}
